basePath: /
definitions:
  models.AppointmentType:
    properties:
      default_length:
        example: 20
        type: integer
      id:
        type: integer
      name:
        example: tarkistus
        type: string
    type: object
  models.AppointmentTypeAddJSON:
    properties:
      default_length:
        example: 20
        type: integer
      name:
        example: laastari
        type: string
    type: object
  models.DeleteFAilResponse:
    properties:
      message:
        example: deleting fail
        type: string
    type: object
  models.DeleteResponse:
    properties:
      message:
        example: delete success
        type: string
    type: object
  models.SearchFailResponse:
    properties:
      message:
        example: searching fail
        type: string
    type: object
  models.UnathenticatedResponse:
    properties:
      message:
        example: unauthenticated
        type: string
    type: object
  models.UpdateResponse:
    properties:
      message:
        example: update success
        type: string
    type: object
host: localhost:5009
info:
  contact: {}
  description: |-
    This App is used to control the appointmentType. It can:
    - Add a new appointmentType
    - Delete the appointmentType
    - Modify the appointmentType
    - Get all appointmentType
  title: Huovet appointmentType API
  version: "1.0"
paths:
  /appointmentType/addAppointmentType:
    post:
      consumes:
      - application/json
      description: Insert new appointmentType to the supplies table in Huovet schema.
      parameters:
      - description: query body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.AppointmentTypeAddJSON'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AppointmentType'
        "401":
          description: Unauthentication
          schema:
            $ref: '#/definitions/models.UnathenticatedResponse'
      security:
      - ApiKeyAuth: []
      summary: Add new appointmentType to database
      tags:
      - AppointmentType
  /appointmentType/deleteAppointmentType/{id}:
    delete:
      consumes:
      - application/json
      description: Remove all the information of the appointmentType.
      parameters:
      - description: AppointmentType ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Delete success
          schema:
            $ref: '#/definitions/models.DeleteResponse'
        "400":
          description: Deleting fail
          schema:
            $ref: '#/definitions/models.DeleteFAilResponse'
        "401":
          description: Unauthentication
          schema:
            $ref: '#/definitions/models.UnathenticatedResponse'
      security:
      - ApiKeyAuth: []
      summary: Delete appointmentType information
      tags:
      - AppointmentType
  /appointmentType/getAllAppointmentType:
    get:
      consumes:
      - application/json
      description: Get all the information of the appointmentTypes.
      produces:
      - application/json
      responses:
        "200":
          description: Search success
          schema:
            items:
              $ref: '#/definitions/models.AppointmentType'
            type: array
        "400":
          description: searching fail
          schema:
            $ref: '#/definitions/models.SearchFailResponse'
        "401":
          description: Unauthentication
          schema:
            $ref: '#/definitions/models.UnathenticatedResponse'
      security:
      - ApiKeyAuth: []
      summary: Get all appointmentType information
      tags:
      - AppointmentType
  /appointmentType/modifyAppointmentType:
    put:
      consumes:
      - application/json
      description: Update the information of the appointmentType.
      parameters:
      - description: query body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.AppointmentType'
      produces:
      - application/json
      responses:
        "200":
          description: Update success
          schema:
            $ref: '#/definitions/models.UpdateResponse'
        "401":
          description: Unauthentication
          schema:
            $ref: '#/definitions/models.UnathenticatedResponse'
      security:
      - ApiKeyAuth: []
      summary: Update appointmentType information
      tags:
      - AppointmentType
schemes:
- http
swagger: "2.0"
